import React,{useEffect,useMemo,useState} from 'react';
import InspectorField from './InspectorField.jsx';
import SpriteStrip from './SpriteStrip.jsx';
import { createCharacterDefinition, VERBS } from '../lib/schema.js';
import { characterAnimationAssetKey, normalizeCharacterAnimationData } from '../lib/animation.js';
import { slugify } from '../lib/id.js';

export default function CharactersEditor({characters,assetUrls,onChange,onChooseAsset,onChooseAnimationAsset,onImport,onExport}){
 const [selectedId,setSelectedId]=useState(characters[0]?.id||'');const [draftName,setDraftName]=useState('');const [draftId,setDraftId]=useState('');const [idTouched,setIdTouched]=useState(false);const [preview,setPreview]=useState({name:'',key:0});
 const selectedRaw=characters.find(c=>c.id===selectedId)||null;const selected=useMemo(()=>selectedRaw?normalizeCharacterAnimationData(selectedRaw):null,[selectedRaw]);
 useEffect(()=>{if(selectedId&&!characters.some(c=>c.id===selectedId))setSelectedId(characters[0]?.id||'')},[characters,selectedId]);
 function add(){const name=draftName.trim(),id=slugify(draftId.trim()||name,'character');if(!name){window.alert('Enter a character name first.');return}if(characters.some(c=>c.id===id)){window.alert(`Character ID “${id}” already exists.`);return}const c={...createCharacterDefinition(name),id,name};onChange([...characters,c]);setSelectedId(c.id);setDraftName('');setDraftId('');setIdTouched(false)}
 function patch(p){if(!selected)return;onChange(characters.map(c=>c.id===selected.id?normalizeCharacterAnimationData({...c,...p}):c))}
 function remove(){if(!selected)return;onChange(characters.filter(c=>c.id!==selected.id));setSelectedId('')}
 function addAnimation(){if(!selected)return;const raw=window.prompt('Animation name (for example: idle, walk, talk, pickup, stampPaper)','idle');if(!raw)return;const name=slugify(raw,'animation');if(selected.animations?.[name]){window.alert(`Animation “${name}” already exists.`);return}patch({animations:{...selected.animations,[name]:{name,src:'',frames:1,fps:8,loop:['idle','walk','talk'].includes(name),frameWidth:0,frameHeight:0,anchorX:.5,anchorY:1,allowHorizontalFlip:true}},defaultAnimation:selected.defaultAnimation||name})}
 function patchAnimation(name,p){patch({animations:{...selected.animations,[name]:{...selected.animations[name],...p,name}}})}
 function renameAnimation(oldName){const raw=window.prompt('Rename animation',oldName);if(!raw)return;const name=slugify(raw,'animation');if(name===oldName)return;if(selected.animations[name]){window.alert(`Animation “${name}” already exists.`);return}const animations={...selected.animations,[name]:{...selected.animations[oldName],name}};delete animations[oldName];const actionAnimations=Object.fromEntries(Object.entries(selected.actionAnimations||{}).map(([verb,value])=>[verb,value===oldName?name:value]));const idleVariants=(selected.idleVariants||[]).map(x=>x===oldName?name:x);patch({animations,actionAnimations,idleVariants,defaultAnimation:selected.defaultAnimation===oldName?name:selected.defaultAnimation});setPreview({name,key:preview.key+1})}
 function deleteAnimation(name){const animations={...selected.animations};delete animations[name];const actionAnimations=Object.fromEntries(Object.entries(selected.actionAnimations||{}).map(([verb,value])=>[verb,value===name?'':value]));patch({animations,actionAnimations,defaultAnimation:selected.defaultAnimation===name?'':selected.defaultAnimation,idleVariants:(selected.idleVariants||[]).filter(x=>x!==name)});if(preview.name===name)setPreview({name:'',key:preview.key+1})}
 const animationNames=selected?Object.keys(selected.animations||{}):[];const previewAnim=selected&&preview.name?selected.animations[preview.name]:null;const previewUrl=selected&&preview.name?assetUrls?.[characterAnimationAssetKey(selected.id,preview.name)]||'':'';
 return <div className="library-layout"><section className="library-list"><div className="character-create-strip"><div><strong>Create character</strong><small>Choose the permanent ID before placing this character into scenes.</small></div><input value={draftName} onChange={e=>{const next=e.target.value;setDraftName(next);if(!idTouched)setDraftId(slugify(next,'character'))}} placeholder="Display name, e.g. Mr. Pindle"/><input value={draftId} onChange={e=>{setIdTouched(true);setDraftId(slugify(e.target.value,'character'))}} placeholder="Character ID, e.g. mr-pindle"/><button className="primary-soft" onClick={add}>Create character</button></div><div className="toolbar"><div className="toolbar-group"><strong>Characters</strong></div><div className="toolbar-group"><button onClick={onImport}>Import</button>{selected&&<button onClick={()=>onExport(selected)}>Export selected</button>}</div></div><div className="library-scroll">{characters.length===0&&<div className="empty-panel">No project characters yet.</div>}{characters.map(c=><button className={`library-row ${selectedId===c.id?'active':''}`} key={c.id} onClick={()=>setSelectedId(c.id)}>{assetUrls?.[`${c.id}:idle`]?<img src={assetUrls[`${c.id}:idle`]} alt=""/>:<span className="library-icon">♙</span>}<span><strong>{c.name}</strong><small>{c.playable?'Playable · ':''}{c.id}.character.json</small></span></button>)}</div></section><aside className="inspector character-animation-inspector"><div className="inspector-title">Character inspector</div>{!selected?<div className="empty-inspector">Select or create a character.</div>:<><div className="object-title-row"><div><strong>{selected.name}</strong><small>{selected.id}.character.json</small></div><button className="danger-ghost" onClick={remove}>Delete</button></div><InspectorField label="ID"><input value={selected.id} readOnly/></InspectorField><InspectorField label="Name"><input value={selected.name} onChange={e=>patch({name:e.target.value})}/></InspectorField><label className="checkbox-row"><input type="checkbox" checked={!!selected.playable} onChange={e=>patch({playable:e.target.checked})}/> Can be controlled by player</label><div className="transform-grid"><InspectorField label="Walk speed"><input type="number" value={selected.walkSpeed||180} onChange={e=>patch({walkSpeed:Number(e.target.value)})}/></InspectorField><InspectorField label="Facing"><select value={selected.defaultFacing||'right'} onChange={e=>patch({defaultFacing:e.target.value})}><option>left</option><option>right</option><option>up</option><option>down</option></select></InspectorField></div><InspectorField label="Notes"><textarea rows="2" value={selected.notes||''} onChange={e=>patch({notes:e.target.value})}/></InspectorField>
 <div className="inspector-divider"/><div className="section-heading-row"><span className="inspector-subtitle">Frame animations</span><button className="small-button" onClick={addAnimation}>+ Animation</button></div><div className="linked-note">Horizontal PNG strips only. All frames should use the same canvas size. Static characters continue to work without animations.</div>
 {animationNames.length===0&&<div className="empty-panel compact">No frame animations yet. Add one or keep using the legacy static sprite slots below.</div>}
 {animationNames.map(name=>{const a=selected.animations[name],url=assetUrls?.[characterAnimationAssetKey(selected.id,name)]||'';return <details className="animation-card" key={name} open={preview.name===name}><summary><strong>{name}</strong><span>{a.frames} frames · {a.fps} fps · {a.loop?'loop':'once'}</span></summary><div className="animation-card-body"><div className="asset-slot-row"><span>Sprite strip</span><code>{a.src||'—'}</code><button onClick={()=>onChooseAnimationAsset(selected.id,name)}>Choose PNG</button></div><div className="animation-config-grid"><InspectorField label="Frames"><input type="number" min="1" value={a.frames||1} onChange={e=>patchAnimation(name,{frames:Math.max(1,Number(e.target.value))})}/></InspectorField><InspectorField label="FPS"><input type="number" min="1" value={a.fps||8} onChange={e=>patchAnimation(name,{fps:Math.max(1,Number(e.target.value))})}/></InspectorField><InspectorField label="Frame W (optional)"><input type="number" min="0" value={a.frameWidth||0} onChange={e=>patchAnimation(name,{frameWidth:Number(e.target.value)})}/></InspectorField><InspectorField label="Frame H (optional)"><input type="number" min="0" value={a.frameHeight||0} onChange={e=>patchAnimation(name,{frameHeight:Number(e.target.value)})}/></InspectorField><InspectorField label="Anchor X"><input type="number" min="0" max="1" step=".01" value={a.anchorX??.5} onChange={e=>patchAnimation(name,{anchorX:Number(e.target.value)})}/></InspectorField><InspectorField label="Anchor Y"><input type="number" min="0" max="1" step=".01" value={a.anchorY??1} onChange={e=>patchAnimation(name,{anchorY:Number(e.target.value)})}/></InspectorField></div><div className="checkbox-grid"><label className="checkbox-row"><input type="checkbox" checked={!!a.loop} onChange={e=>patchAnimation(name,{loop:e.target.checked})}/> Loop</label><label className="checkbox-row"><input type="checkbox" checked={a.allowHorizontalFlip!==false} onChange={e=>patchAnimation(name,{allowHorizontalFlip:e.target.checked})}/> Allow horizontal mirror</label></div><div className="animation-card-actions"><button onClick={()=>setPreview({name,key:preview.key+1})}>▶ Preview</button><button onClick={()=>renameAnimation(name)}>Rename</button><button className="danger-ghost" onClick={()=>deleteAnimation(name)}>Delete</button></div>{preview.name===name&&<div className="animation-preview-box">{url?<SpriteStrip src={url} animation={a} playKey={preview.key} className="animation-preview-sprite"/>:<span>Choose a sprite strip to preview.</span>}</div>}</div></details>})}
 <InspectorField label="Default animation"><select value={selected.defaultAnimation||''} onChange={e=>patch({defaultAnimation:e.target.value})}><option value="">Static / legacy idle</option>{animationNames.map(n=><option key={n}>{n}</option>)}</select></InspectorField>
 <div className="inspector-divider"/><div className="inspector-subtitle">Action → animation mapping</div>{VERBS.filter(v=>v!=='walk'||true).map(verb=><div className="animation-map-row" key={verb}><span>{verb==='pickUp'?'Pick up':verb}</span><select value={selected.actionAnimations?.[verb]||''} onChange={e=>patch({actionAnimations:{...selected.actionAnimations,[verb]:e.target.value}})}><option value="">No animation / fallback</option>{animationNames.map(n=><option key={n}>{n}</option>)}</select></div>)}
 <div className="inspector-divider"/><details><summary className="inspector-subtitle">Legacy/static fallback assets</summary>{['portrait','idle','walkLeft','walkRight','walkUp','walkDown'].map(slot=><div className="asset-slot-row" key={slot}><span>{slot}</span><code>{selected.assets?.[slot]||'—'}</code><button onClick={()=>onChooseAsset(selected.id,slot)}>Choose</button></div>)}</details></>}</aside></div>
}
