import React,{useState} from 'react';
import InspectorField from './InspectorField.jsx';
import { createCharacterDefinition } from '../lib/schema.js';

export default function CharactersEditor({characters,assetUrls,onChange,onChooseAsset,onImport,onExport}){
 const [selectedId,setSelectedId]=useState(characters[0]?.id||''); const selected=characters.find(c=>c.id===selectedId)||null;
 function add(){const c=createCharacterDefinition(`Character ${characters.length+1}`);onChange([...characters,c]);setSelectedId(c.id)}
 function patch(p){onChange(characters.map(c=>c.id===selected.id?{...c,...p}:c))}
 function remove(){onChange(characters.filter(c=>c.id!==selected.id));setSelectedId('')}
 return <div className="library-layout"><section className="library-list"><div className="toolbar"><div className="toolbar-group"><strong>Characters</strong><button className="primary-soft" onClick={add}>+ Character</button></div><div className="toolbar-group"><button onClick={onImport}>Import</button>{selected&&<button onClick={()=>onExport(selected)}>Export selected</button>}</div></div><div className="library-scroll">{characters.length===0&&<div className="empty-panel">No project characters yet. Scene character objects can reference definitions created here.</div>}{characters.map(c=><button className={`library-row ${selectedId===c.id?'active':''}`} key={c.id} onClick={()=>setSelectedId(c.id)}>{assetUrls?.[`${c.id}:idle`]?<img src={assetUrls[`${c.id}:idle`]} alt=""/>:<span className="library-icon">♙</span>}<span><strong>{c.name}</strong><small>{c.playable?'Playable · ':''}{c.id}.character.json</small></span></button>)}</div></section><aside className="inspector"><div className="inspector-title">Character inspector</div>{!selected?<div className="empty-inspector">Select or create a character.</div>:<><div className="object-title-row"><div><strong>{selected.name}</strong><small>{selected.id}.character.json</small></div><button className="danger-ghost" onClick={remove}>Delete</button></div><InspectorField label="ID"><input value={selected.id} readOnly/></InspectorField><InspectorField label="Name"><input value={selected.name} onChange={e=>patch({name:e.target.value})}/></InspectorField><label className="checkbox-row"><input type="checkbox" checked={!!selected.playable} onChange={e=>patch({playable:e.target.checked})}/> Can be controlled by player</label><div className="transform-grid"><InspectorField label="Walk speed"><input type="number" value={selected.walkSpeed||180} onChange={e=>patch({walkSpeed:Number(e.target.value)})}/></InspectorField><InspectorField label="Facing"><select value={selected.defaultFacing||'right'} onChange={e=>patch({defaultFacing:e.target.value})}><option>left</option><option>right</option><option>up</option><option>down</option></select></InspectorField></div><InspectorField label="Notes"><textarea rows="3" value={selected.notes||''} onChange={e=>patch({notes:e.target.value})}/></InspectorField><div className="inspector-divider"/><div className="inspector-subtitle">Animation slots</div>{['portrait','idle','walkLeft','walkRight','walkUp','walkDown'].map(slot=><div className="asset-slot-row" key={slot}><span>{slot}</span><code>{selected.assets?.[slot]||'—'}</code><button onClick={()=>onChooseAsset(selected.id,slot)}>Choose</button></div>)}</>}</aside></div>
}
