import React,{useState} from 'react';
import { orderedScenes } from '../lib/sceneManager.js';
function sceneNumber(scene,index){const match=String(scene.id||'').match(/^scene(\d+)$/);return match?String(Number(match[1])).padStart(2,'0'):String(index+1).padStart(2,'0')}
const NAV=[['scenes','Scenes','▦'],['sceneManager','Scene Manager','⇄'],['characters','Characters','♙'],['inventory','Inventory','◇'],['ui','Game UI','▤'],['variables','Variables','ƒ'],['strings','Text & Translation','¶'],['validation','Playability Check','✓'],['settings','Settings','⚙']];
export default function SceneList({project,sceneManager,activeSceneId,activePanel,onOpenScene,onCreateScene,onImportScene,onSelectPanel,onCloseProject}){
 const [creating,setCreating]=useState(false);const [name,setName]=useState('New Scene');const [sceneType,setSceneType]=useState('gameplay');const scenes=orderedScenes(project.scenes,sceneManager);
 function submit(){const v=name.trim();if(!v)return;onCreateScene(v,sceneType);setCreating(false);setName('New Scene');setSceneType('gameplay')}
 return <aside className="scene-sidebar"><div className="scene-sidebar-head"><div><div className="eyebrow">Project</div><div className="project-name">{project.name}</div></div><button className="icon-button" title="Close project" onClick={onCloseProject}>×</button></div><div className="project-nav">{NAV.map(([id,label,icon])=><button key={id} className={activePanel===id?'active':''} onClick={()=>onSelectPanel(id)}><span>{icon}</span>{label}</button>)}</div>{activePanel==='scenes'&&<><div className="sidebar-section-title"><span>Scenes</span><div className="sidebar-import-row"><button className="small-button" onClick={onImportScene}>Import</button><button className="small-button" onClick={()=>setCreating(true)}>+ New</button></div></div><div className="scene-list">{scenes.length===0&&<div className="empty-sidebar">No scenes yet.</div>}{scenes.map((scene,index)=><button key={scene.id} className={`scene-row ${activeSceneId===scene.id?'active':''}`} onClick={()=>onOpenScene(scene)}><span className="scene-index">{sceneNumber(scene,index)}</span><span><strong>{scene.name}</strong><small>{scene.id}{scene.sceneType==='title'?' · title':''}</small></span></button>)}</div></>}{creating&&<div className="modal-backdrop" onMouseDown={()=>setCreating(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><h2>Create scene</h2><label>Scene name</label><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} autoFocus/><label>Scene type</label><select value={sceneType} onChange={e=>setSceneType(e.target.value)}><option value="gameplay">Gameplay scene</option><option value="title">Title / Home screen (Scene 0)</option></select>{sceneType==='title'&&<p className="muted">A title screen has its own background, title, New Game and Load Game buttons and never renders the normal project GUI.</p>}<div className="modal-actions"><button onClick={()=>setCreating(false)}>Cancel</button><button className="primary" onClick={submit}>Create scene</button></div></div></div>}</aside>
}
