import React,{useState} from 'react';
import InspectorField from './InspectorField.jsx';
import { VARIABLE_TYPES } from '../lib/schema.js';
import { slugify } from '../lib/id.js';

export default function VariablesEditor({variables,onChange,onImport,onExport}){
 const list=variables.variables||[]; const [selectedId,setSelectedId]=useState(list[0]?.id||''); const selected=list.find(v=>v.id===selectedId)||null;
 function add(){let id=`variable-${list.length+1}`;const v={id,name:`Variable ${list.length+1}`,type:'boolean',initialValue:false};onChange({...variables,variables:[...list,v]});setSelectedId(id)}
 function patch(p){onChange({...variables,variables:list.map(v=>v.id===selected.id?{...v,...p}:v)})}
 function remove(){onChange({...variables,variables:list.filter(v=>v.id!==selected.id)});setSelectedId('')}
 return <div className="library-layout"><section className="library-list"><div className="toolbar"><div className="toolbar-group"><strong>Global variables</strong><button className="primary-soft" onClick={add}>+ Variable</button></div><div className="toolbar-group"><button onClick={onImport}>Import</button><button onClick={onExport}>Export</button></div></div><div className="library-scroll">{list.length===0&&<div className="empty-panel">No global variables. These survive scene changes and saves.</div>}{list.map(v=><button className={`library-row ${v.id===selectedId?'active':''}`} key={v.id} onClick={()=>setSelectedId(v.id)}><span className="library-icon">ƒ</span><span><strong>{v.name}</strong><small>{v.id} · {v.type} = {String(v.initialValue)}</small></span></button>)}</div></section><aside className="inspector"><div className="inspector-title">Variable inspector</div>{!selected?<div className="empty-inspector">Select or create a variable.</div>:<><div className="object-title-row"><div><strong>{selected.name}</strong><small>project.variables.json</small></div><button className="danger-ghost" onClick={remove}>Delete</button></div><InspectorField label="ID"><input value={selected.id} onChange={e=>patch({id:slugify(e.target.value,'variable')})}/></InspectorField><InspectorField label="Name"><input value={selected.name} onChange={e=>patch({name:e.target.value})}/></InspectorField><InspectorField label="Type"><select value={selected.type} onChange={e=>patch({type:e.target.value,initialValue:e.target.value==='boolean'?false:e.target.value==='number'?0:''})}>{VARIABLE_TYPES.map(t=><option key={t}>{t}</option>)}</select></InspectorField><InspectorField label="Initial value">{selected.type==='boolean'?<select value={String(selected.initialValue)} onChange={e=>patch({initialValue:e.target.value==='true'})}><option value="false">false</option><option value="true">true</option></select>:<input type={selected.type==='number'?'number':'text'} value={selected.initialValue} onChange={e=>patch({initialValue:selected.type==='number'?Number(e.target.value):e.target.value})}/>}</InspectorField></>}</aside></div>
}
