import React,{useEffect,useRef,useState} from 'react';
import SceneList from './SceneList.jsx';
import VisualEditor from './VisualEditor.jsx';
import LogicEditor from './LogicEditor.jsx';
import DialogueEditor from './DialogueEditor.jsx';
import GameUiEditor from './GameUiEditor.jsx';
import InventoryEditor from './InventoryEditor.jsx';
import CharactersEditor from './CharactersEditor.jsx';
import VariablesEditor from './VariablesEditor.jsx';
import SettingsEditor from './SettingsEditor.jsx';
import RuntimePlayer from './RuntimePlayer.jsx';
import { copyAssetIntoScene,copyProjectAsset,readProjectAssetUrl,readSceneAssetUrl,createScene,importJsonFiles,loadProjectBundle,loadSceneBundle,saveProjectBundle,saveSceneBundle } from '../lib/projectFs.js';
import { createCharacterDefinition } from '../lib/schema.js';

function downloadJson(filename,value){const blob=new Blob([`${JSON.stringify(value,null,2)}\n`],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function pickFiles(accept,multiple=false){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept=accept;input.multiple=multiple;input.onchange=()=>resolve(input.files);input.click()})}
async function pickImage(){const files=await pickFiles('image/png,image/webp,image/jpeg');return files?.[0]||null}
async function pickAudio(){const files=await pickFiles('audio/mpeg,audio/wav,audio/ogg,.mp3,.wav,.ogg');return files?.[0]||null}

export default function Workspace({rootHandle,initialProject,onCloseProject}){
 const [project,setProject]=useState(initialProject);const [projectData,setProjectData]=useState(null);const projectDataRef=useRef(null);const [activePanel,setActivePanel]=useState('scenes');const [activeScene,setActiveScene]=useState(null);const [bundle,setBundle]=useState(null);const bundleRef=useRef(null);const [tab,setTab]=useState('visual');const [saveStatus,setSaveStatus]=useState('Loading…');const [error,setError]=useState('');const [playOpen,setPlayOpen]=useState(false);const sceneTimer=useRef(null),projectTimer=useRef(null);const sceneHistory=useRef({past:[],future:[],last:0});const projectHistory=useRef({past:[],future:[],last:0});const [historyTick,setHistoryTick]=useState(0);
 useEffect(()=>{loadProjectBundle(rootHandle,initialProject).then(data=>{projectDataRef.current=data;setProjectData(data);setSaveStatus('Saved')}).catch(e=>{setError(e.message);setSaveStatus('Error')});return()=>{clearTimeout(sceneTimer.current);clearTimeout(projectTimer.current)}},[]);
 async function openScene(scene){try{sceneHistory.current={past:[],future:[],last:0};setHistoryTick(v=>v+1);setError('');setSaveStatus('Loading…');const loaded=await loadSceneBundle(rootHandle,scene);bundleRef.current=loaded;setBundle(loaded);setActiveScene(scene);setActivePanel('scenes');setSaveStatus('Saved')}catch(e){setError(e.message);setSaveStatus('Error')}}
 async function addScene(name){try{setSaveStatus('Creating…');const result=await createScene(rootHandle,project,name);setProject(result.project);const scene=result.project.scenes.find(s=>s.id===result.sceneId);await openScene(scene);if(!projectDataRef.current.settings.defaultSceneId)changeProjectField('settings',{...projectDataRef.current.settings,defaultSceneId:scene.id})}catch(e){setError(e.message);setSaveStatus('Error')}}
 function scheduleSceneSave(next){if(!activeScene)return;bundleRef.current=next;setSaveStatus('Unsaved');clearTimeout(sceneTimer.current);sceneTimer.current=setTimeout(async()=>{try{setSaveStatus('Saving…');await saveSceneBundle(rootHandle,activeScene,bundleRef.current);setSaveStatus('Saved')}catch(e){setError(e.message);setSaveStatus('Error')}},400)}
 function recordHistory(holder,value){const now=Date.now();if(now-holder.current.last>250){holder.current.past=[...holder.current.past.slice(-49),structuredClone(value)];holder.current.future=[];holder.current.last=now;setHistoryTick(v=>v+1)}}
 function changeField(field,value){recordHistory(sceneHistory,bundleRef.current);const next={...bundleRef.current,[field]:value};bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}
 function scheduleProjectSave(next){projectDataRef.current=next;setSaveStatus('Unsaved');clearTimeout(projectTimer.current);projectTimer.current=setTimeout(async()=>{try{setSaveStatus('Saving…');await saveProjectBundle(rootHandle,projectDataRef.current);setSaveStatus('Saved')}catch(e){setError(e.message);setSaveStatus('Error')}},400)}
 function changeProjectField(field,value){recordHistory(projectHistory,projectDataRef.current);const next={...projectDataRef.current,[field]:value};projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}
 function activeHistory(){return activePanel==='scenes'&&activeScene?sceneHistory:projectHistory}
 function undo(){const holder=activeHistory();const h=holder.current;if(!h.past.length)return;if(activePanel==='scenes'&&activeScene){const current=structuredClone(bundleRef.current);const prev=h.past[h.past.length-1];h.past=h.past.slice(0,-1);h.future=[current,...h.future].slice(0,50);bundleRef.current=prev;setBundle(prev);scheduleSceneSave(prev)}else{const current=structuredClone(projectDataRef.current);const prev=h.past[h.past.length-1];h.past=h.past.slice(0,-1);h.future=[current,...h.future].slice(0,50);projectDataRef.current=prev;setProjectData(prev);scheduleProjectSave(prev)}setHistoryTick(v=>v+1)}
 function redo(){const holder=activeHistory();const h=holder.current;if(!h.future.length)return;if(activePanel==='scenes'&&activeScene){const current=structuredClone(bundleRef.current);const next=h.future[0];h.future=h.future.slice(1);h.past=[...h.past,current].slice(-50);bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}else{const current=structuredClone(projectDataRef.current);const next=h.future[0];h.future=h.future.slice(1);h.past=[...h.past,current].slice(-50);projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}setHistoryTick(v=>v+1)}
 function ensureCharacter(id,name){if(projectDataRef.current.characters.some(c=>c.id===id))return;const c={...createCharacterDefinition(name),id,name};changeProjectField('characters',[...projectDataRef.current.characters,c])}
 async function chooseSceneAsset(objectId,state='default'){const file=await pickImage();if(!file)return;try{const path=await copyAssetIntoScene(rootHandle,activeScene,file);const url=await readSceneAssetUrl(rootHandle,activeScene,path);const objects=bundleRef.current.objects.map(o=>{if(o.id!==objectId)return o;const states={...(o.asset?.states||{}),[state]:path};return{...o,asset:{...o.asset,states,state:o.asset?.state||'default',path:state===(o.asset?.state||'default')?path:o.asset?.path}}});const assetUrls={...bundleRef.current.assetUrls,[objectId]:state===(objects.find(o=>o.id===objectId)?.asset?.state||'default')?url:bundleRef.current.assetUrls[objectId]};const stateAssetUrls={...bundleRef.current.stateAssetUrls,[`${objectId}:${path}`]:url};const next={...bundleRef.current,objects,assetUrls,stateAssetUrls};bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}catch(e){setError(e.message)}}
 async function chooseBackground(){const file=await pickImage();if(!file)return;try{const path=await copyAssetIntoScene(rootHandle,activeScene,file);const url=await readSceneAssetUrl(rootHandle,activeScene,path);const visual={...bundleRef.current.visual,background:{...bundleRef.current.visual.background,path}};const next={...bundleRef.current,visual,assetUrls:{...bundleRef.current.assetUrls,__background:url}};bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}catch(e){setError(e.message)}}
 async function chooseSceneAudio(slot){const file=await pickAudio();if(!file)return;try{const path=await copyAssetIntoScene(rootHandle,activeScene,file);const url=await readSceneAssetUrl(rootHandle,activeScene,path);const meta={...bundleRef.current.meta,audio:{...(bundleRef.current.meta.audio||{}),[slot]:path}};const next={...bundleRef.current,meta,assetUrls:{...bundleRef.current.assetUrls,[`__${slot}`]:url}};bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}catch(e){setError(e.message)}}
 async function chooseProjectAsset(category,id,slot=null){const file=await pickImage();if(!file)return;try{const path=await copyProjectAsset(rootHandle,category,file);const url=await readProjectAssetUrl(rootHandle,category,path);if(category==='inventory'){const items=projectDataRef.current.inventory.map(i=>i.id===id?{...i,asset:path}:i);const next={...projectDataRef.current,inventory:items,assetUrls:{...projectDataRef.current.assetUrls,inventory:{...projectDataRef.current.assetUrls.inventory,[id]:url}}};projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}if(category==='characters'){const chars=projectDataRef.current.characters.map(c=>c.id===id?{...c,assets:{...c.assets,[slot]:path}}:c);const next={...projectDataRef.current,characters:chars,assetUrls:{...projectDataRef.current.assetUrls,characters:{...projectDataRef.current.assetUrls.characters,[`${id}:${slot}`]:url}}};projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}if(category==='ui'){const ui={...projectDataRef.current.ui,elements:projectDataRef.current.ui.elements.map(el=>el.id===id?{...el,asset:path}:el)};const next={...projectDataRef.current,ui,assetUrls:{...projectDataRef.current.assetUrls,ui:{...projectDataRef.current.assetUrls.ui,[id]:url}}};projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}}catch(e){setError(e.message)}}
 async function chooseCursor(verb){const file=await pickImage();if(!file)return;try{const path=await copyProjectAsset(rootHandle,'ui',file);const url=await readProjectAssetUrl(rootHandle,'ui',path);const ui={...projectDataRef.current.ui,cursors:{...(projectDataRef.current.ui.cursors||{}),[verb]:path}};const next={...projectDataRef.current,ui,assetUrls:{...projectDataRef.current.assetUrls,ui:{...projectDataRef.current.assetUrls.ui,[`cursor:${verb}`]:url}}};projectDataRef.current=next;setProjectData(next);scheduleProjectSave(next)}catch(e){setError(e.message)}}
 async function importVisual(){const files=await pickFiles('.json,application/json',true);if(!files?.length)return;try{const imported=await importJsonFiles(files);let nextVisual=bundleRef.current.visual,nextObjects=[...bundleRef.current.objects];for(const v of imported){if(v.sceneId&&v.sceneId!==activeScene.id)throw new Error(`Imported ${v.kind||'file'} belongs to ${v.sceneId}.`);if(v.kind==='scemq-scene-visual')nextVisual=v;if(v.kind==='scemq-scene-object'){nextObjects=[...nextObjects.filter(o=>o.id!==v.id),v];if(!(nextVisual.objectRefs||[]).includes(v.id))nextVisual={...nextVisual,objectRefs:[...(nextVisual.objectRefs||[]),v.id]}};if(v.kind==='scemq-visual-package'){nextVisual=v.visual;nextObjects=v.objects}}const next={...bundleRef.current,visual:nextVisual,objects:nextObjects};bundleRef.current=next;setBundle(next);scheduleSceneSave(next)}catch(e){setError(e.message)}}
 async function importLogic(){const files=await pickFiles('.json,application/json');if(!files?.length)return;try{const [v]=await importJsonFiles(files);if(v.kind!=='scemq-scene-logic'||v.sceneId!==activeScene.id)throw new Error('That is not logic for this scene.');changeField('logic',v)}catch(e){setError(e.message)}}
 async function importDialogue(){const files=await pickFiles('.json,application/json',true);if(!files?.length)return;try{const imported=await importJsonFiles(files);let next=[...bundleRef.current.dialogues];for(const v of imported){if(v.kind!=='scemq-scene-dialogue'||v.sceneId!==activeScene.id)throw new Error('One dialogue file does not belong to this scene.');next=[...next.filter(d=>d.characterId!==v.characterId),v]}changeField('dialogues',next)}catch(e){setError(e.message)}}
 async function importProjectModule(kind){const files=await pickFiles('.json,application/json',kind==='character'||kind==='inventory');if(!files?.length)return;try{const values=await importJsonFiles(files);if(kind==='character'){let next=[...projectDataRef.current.characters];for(const v of values){if(v.kind!=='scemq-character')throw new Error('One file is not a SCEMQ character definition.');next=[...next.filter(x=>x.id!==v.id),v]}changeProjectField('characters',next)}if(kind==='inventory'){let next=[...projectDataRef.current.inventory];for(const v of values){if(v.kind!=='scemq-inventory-item')throw new Error('One file is not a SCEMQ inventory item.');next=[...next.filter(x=>x.id!==v.id),v]}changeProjectField('inventory',next)}if(kind==='ui'){const v=values[0];if(v.kind!=='scemq-project-ui')throw new Error('That file is not SCEMQ Game UI.');changeProjectField('ui',v)}if(kind==='variables'){const v=values[0];if(v.kind!=='scemq-project-variables')throw new Error('That file is not SCEMQ project variables.');changeProjectField('variables',v)}if(kind==='settings'){const v=values[0];if(v.kind!=='scemq-project-settings')throw new Error('That file is not SCEMQ project settings.');changeProjectField('settings',v)}}catch(e){setError(e.message)}}
 function selectPanel(id){setActivePanel(id);if(id!=='scenes'){setActiveScene(null);setBundle(null);setPlayOpen(false)}}
 function exportVisual(){downloadJson(`visual.package.${activeScene.id}.json`,{schemaVersion:'0.2',kind:'scemq-visual-package',sceneId:activeScene.id,visual:bundle.visual,objects:bundle.objects})}
 if(!projectData)return <div className="hub-shell"><div className="hub-card"><h2>Loading SCEMQ project…</h2></div></div>;
 return <div className="workspace-shell"><SceneList project={project} activeSceneId={activeScene?.id} activePanel={activePanel} onOpenScene={openScene} onCreateScene={addScene} onSelectPanel={selectPanel} onCloseProject={onCloseProject}/><section className="workspace-main"><header className="workspace-header"><div className="workspace-brand"><span className="mini-brand">S</span><span>SCEMQ</span></div><div className="scene-heading"><strong>{activeScene?activeScene.name:({scenes:'Project scenes',characters:'Characters',inventory:'Inventory',ui:'Game UI',variables:'Variables',settings:'Settings'}[activePanel])}</strong><span>{activeScene?activeScene.id:'SCEMQ project authoring'}</span></div><div className="header-actions"><div className="undo-group"><button disabled={!activeHistory().current.past.length} onClick={undo} title="Undo">↶</button><button disabled={!activeHistory().current.future.length} onClick={redo} title="Redo">↷</button></div>{activeScene&&<button className="play-button" onClick={()=>setPlayOpen(true)}>▶ Play Scene</button>}<div className={`save-status ${saveStatus.toLowerCase().replace('…','')}`}><span className="status-dot"/>{saveStatus}</div></div></header>{error&&<div className="workspace-error"><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
 {activePanel==='characters'&&<CharactersEditor characters={projectData.characters} assetUrls={projectData.assetUrls.characters} onChange={v=>changeProjectField('characters',v)} onChooseAsset={(id,slot)=>chooseProjectAsset('characters',id,slot)} onImport={()=>importProjectModule('character')} onExport={c=>downloadJson(`${c.id}.character.json`,c)}/>} {activePanel==='inventory'&&<InventoryEditor items={projectData.inventory} assetUrls={projectData.assetUrls.inventory} onChange={v=>changeProjectField('inventory',v)} onChooseAsset={id=>chooseProjectAsset('inventory',id)} onImport={()=>importProjectModule('inventory')} onExport={i=>downloadJson(`${i.id}.item.json`,i)}/>} {activePanel==='ui'&&<GameUiEditor ui={projectData.ui} assetUrls={projectData.assetUrls.ui} onChange={v=>changeProjectField('ui',v)} onChooseAsset={id=>chooseProjectAsset('ui',id)} onChooseCursor={chooseCursor} onImport={()=>importProjectModule('ui')} onExport={()=>downloadJson('project.ui.json',projectData.ui)}/>} {activePanel==='variables'&&<VariablesEditor variables={projectData.variables} onChange={v=>changeProjectField('variables',v)} onImport={()=>importProjectModule('variables')} onExport={()=>downloadJson('project.variables.json',projectData.variables)}/>} {activePanel==='settings'&&<SettingsEditor settings={projectData.settings} scenes={project.scenes} onChange={v=>changeProjectField('settings',v)} onImport={()=>importProjectModule('settings')} onExport={()=>downloadJson('project.settings.json',projectData.settings)}/>} 
 {activePanel==='scenes'&&(!activeScene||!bundle?<div className="welcome-workspace"><div className="welcome-icon">⌘</div><h2>{project.scenes.length?'Choose a scene to author':'Create your first scene'}</h2><p>Scenes are authored as Visual Config, Logic and Dialogues. Project-wide characters, inventory and GUI live in the left navigation.</p>{!project.scenes.length&&<button className="primary" onClick={()=>addScene('Scene 1')}>Create Scene 1</button>}</div>:<><nav className="author-tabs"><button className={tab==='visual'?'active':''} onClick={()=>setTab('visual')}><span>01</span> Visual Config</button><button className={tab==='logic'?'active':''} onClick={()=>setTab('logic')}><span>02</span> Logic</button><button className={tab==='dialogue'?'active':''} onClick={()=>setTab('dialogue')}><span>03</span> Dialogues</button></nav><div className="author-surface">{tab==='visual'&&<VisualEditor sceneId={activeScene.id} meta={bundle.meta} visual={bundle.visual} objects={bundle.objects} assetUrls={bundle.assetUrls} stateAssetUrls={bundle.stateAssetUrls} logic={bundle.logic} project={project} characters={projectData.characters} gameUi={projectData.ui} onChangeVisual={v=>changeField('visual',v)} onChangeObjects={v=>changeField('objects',v)} onChooseAsset={chooseSceneAsset} onChooseBackground={chooseBackground} onChooseSceneAudio={chooseSceneAudio} onChangeMeta={v=>changeField('meta',v)} onEnsureCharacter={ensureCharacter} onImport={importVisual} onExport={exportVisual}/>} {tab==='logic'&&<LogicEditor sceneId={activeScene.id} logic={bundle.logic} objects={bundle.objects} items={projectData.inventory} globalVariables={projectData.variables.variables||[]} scenes={project.scenes} characters={projectData.characters} onChange={v=>changeField('logic',v)} onImport={importLogic} onExport={()=>downloadJson(`scene.logic.${activeScene.id}.json`,bundle.logic)}/>} {tab==='dialogue'&&<DialogueEditor sceneId={activeScene.id} objects={bundle.objects} dialogues={bundle.dialogues} items={projectData.inventory} globalVariables={projectData.variables.variables||[]} scenes={project.scenes} projectCharacters={projectData.characters} onChangeDialogues={v=>changeField('dialogues',v)} onImport={importDialogue} onExport={d=>downloadJson(`${d.characterId}.dialogue.${activeScene.id}.json`,d)}/>}</div></>)}
 </section>{playOpen&&activeScene&&<RuntimePlayer project={project} projectData={projectData} initialScene={activeScene} loadScene={ref=>loadSceneBundle(rootHandle,ref)} onClose={()=>setPlayOpen(false)}/>}</div>
}
